### ISSUE TITLE
Improve the game selection Pimple/Rash artworks

### ISSUE THREAD

**Issue by AlWesker** [maxim-zhao/battlemaniacs-restoration#11]
The Master System versions had some redrawn artworks for both the Battlemaniacs logo in the title screen and Pimple and Rash in the selection screen (these artworks also appear in the continue and game complete screens). It may be possible to replace these with reconverted versions which are more accurate to the SNES originals. Converted artworks for Pimple and Rash are already in place in src/images/Pyron which whould be compatible tile/color wise. There's also a converted artwork for the Battlemaniacs logo which unfortunately seems to hit the maximum tile limit (it hits 270 tiles). If it's difficult to repurpose this suggested artwork, another possibility may be color readapting the existing Master System logo (which is a little drab color wise) to something closer to the suggested SNES converted artwork.

**Comment by maxim-zhao** [comment]
Title is done (see #6), the character art may be mildly more tricky depending on how we want to deal with the game over screen - if it uses the same art it's a little more tricky. Can you explain how the game over/continue flow should (ideally) work in another issue, maybe with a YouTube reference?

**Comment by AlWesker** [comment]
Right. I'll do it. It's true the Master System version behaves differently than the SNES version regarding the artworks of the selection screen (SNES uses those artworks), game over screen (SNES uses different artworks) and game complete screen (SNES version doesn't have a proper game complete screen showing any artwork). Master System version reuses the same artworks for those same three instances. I'll open another issue and explain it better there.

**Comment by maxim-zhao** [comment]
I've done a little work on the character artworks, The newer art is 96x112px, wheras the SMS art is 96x96; the extra 16px probably make the circles more circular on a TV (the SMS pixel aspect ratio is not square, especially for PAL) but it makes it hard to make it fit, and it looks stretched in most emulators.

@PyronsLair Can you unstretch it a bit? Alternatively/additionally, could you "burn in" the Pimple and Rash names (maybe using a suitable fancy font) so I can use some of the space where the names currently go?

**Comment by PyronsLair** [comment]
need watch it in the game to do the correction, is possible send me a rom ?


2018-08-03 11:54 GMT-03:00 Maxim <notifications@github.com>:

**Comment by AlWesker** [comment]
About using a suitable fancy font to burn in the Pimple and Rash names, maybe it could be done with a fancy font similar to the one that the SNES version uses for 1 PLAYER, 2 PLAYERS A and 2 PLAYERS B modes.

![imagen](https://user-images.githubusercontent.com/41370804/43672387-1e4d3878-97ad-11e8-9815-c7500ea04d6a.png)

I tried to rip that but it seems it's not a proper font, just those spare letters buried as graphics. Any idea about a similar fancy font? Would be a neat touch.

**Comment by maxim-zhao** [comment]
Before:
![image](https://user-images.githubusercontent.com/7792986/43667457-e3ecb574-976f-11e8-8a0b-901bd2ef6dec.png)
After:
![image](https://user-images.githubusercontent.com/7792986/43667472-ef1b370e-976f-11e8-9eeb-668abb99df09.png)

**Comment by PyronsLair** [comment]
looks bad for me....

I need look at it on console and strechted..  to do the corrections...
because the artwork on snes is made to be strechted..

I can draw the name on the top of characters.. also put them near of the
border on the screen


2018-08-03 18:54 GMT-03:00 Maxim <notifications@github.com>:

**Comment by AlWesker** [comment]
I have another idea. If you can use additional space where the names go, then why not omitting the names? As you can see, the SNES player selection screen didn't have them.

![imagen](https://user-images.githubusercontent.com/41370804/43672313-b052ff3e-97ab-11e8-9e46-dfe802089342.png)

In case a toad selection screen could be done (hard, but maybe possible) to manually choose the toad and solve out the problem with Rash and its controller input, then maybe the names could be brought back in and placed below the artworks, instead of above like they are now, and create some kind of toad select choice system with arrows or Player 1/1P and Player 2/2P moving letters or something like that. In that case it would make more sense for the names to appear on that toad selection screen (like arcade beat 'em ups or fighters typically do) and given that the names would be placed below (and those 1 Player, 2 Players A, 2 Players B and Options of the selection screen wouldn't be there to take space), there wouldn't be the same problem with fitting space that there's now.

**Comment by maxim-zhao** [comment]
For future reference, you can right click to could a picture and then just Ctrl-V to paste in here.

Maybe the character names from the game over screen could be scaled down and used?

**Comment by PyronsLair** [comment]
Why just did equally of snes version?  I think that we have tiles left for
the big fonts either..

To select the character the right solution I'd change to green the color
the circle around then..  And don't put the name above them

Em sex, 3 de ago de 2018 19:53, Maxim <notifications@github.com> escreveu:

**Comment by AlWesker** [comment]
Thanks for the tip, Maxim. I was actually wondering how that was done.

Try and see how it fits, Pyron. Don't know if maybe the character names from the Game Over screens would be too big to fit within the circles, even if scaled down, but I suppose you could try.

**Comment by maxim-zhao** [comment]
Let's leave character selection out for now - I just want to finish off this screen.

**Comment by AlWesker** [comment]
A little mockup I just did.

![imagen](https://user-images.githubusercontent.com/41370804/43676223-4962ccfe-97ed-11e8-8e49-d9b291f1ab1c.png)

Doesn't seem too bad this way.

There's also the possibility of placing the text choices a little lower so the original gap between them and the artworks would be restored.

![imagen](https://user-images.githubusercontent.com/41370804/43676294-96c932c0-97ee-11e8-81c8-0b93d9b8e341.png)

**Comment by PyronsLair** [comment]
If you have options you dosent need player A and B

2018-08-04 8:50 GMT-03:00 Albert Wesker <notifications@github.com>:

**Comment by PyronsLair** [comment]
https://i.imgur.com/kr4U6Nl.png

take a look

2018-08-04 12:19 GMT-03:00 Gabriel Pyron <gabpyron@gmail.com>:

**Comment by AlWesker** [comment]
The "2 Players A" and "2 Players B" difference determine whether friendly fire is enabled (A) or not (B). It's just put that way both in the SNES and Master System versions of Battletoads in Battlemaniacs and also in the NES, Mega Drive and SNES versions of Battletoads Double Dragon (the Game Boy version of the latter lacks it due to being 1 player only). Removing that would require to add a friendly fire setting in the options menu which of course would make for less choices in the selection menu and more room for the artwork, but I'm not sure if that's worth the hassle. I actually see it fine that way.

**Comment by PyronsLair** [comment]
Dude,  I already know all that..  But all these versions you have 2 players
A other B because you don't have options menu to choose 2p damage on or off
like every game.   So if you have options you must have to remove it..
Simple..  Now if you remove options back to all things considered at
normal..  What is in my opinion the correct to do.

Em sáb, 4 de ago de 2018 21:39, Albert Wesker <notifications@github.com>
escreveu:

**Comment by PyronsLair** [comment]
Also in opitions we can add a extra feature..  Players orders: so you can
choose if player 1 gonna be rash or piple and vice versa

Em dom, 5 de ago de 2018 09:51, Gabriel Pyron <gabpyron@gmail.com> escreveu:

**Comment by maxim-zhao** [comment]
Editing the options menus (and even moving the main menu down) is hard work. Are we going to unstretch the art?

**Comment by PyronsLair** [comment]
The menu and etc.. i don't put it on table, if want keep to original is
fine.. its just a sugestion to give more room to use some cool fancy fonts
to pimple and rash like you have demanded before.

About the art.. like i said before i must see the problem to do the
corrections..
because in emulator i capture from vdp the resolution of 256x240.. the snes
artwork is correct.. the screen runs at 256x224.. both of them will be
scaled to TV in 4:3 aspect ratio.. tha art on snes is concepted to be
strech and looks correct on TV and on real hardware.

So if you set the image to SMS resolution given to me in emulator and
stretch it as must be strechted the art looks perfect as must be..

https://i.imgur.com/xeedLbF.png

because it i must see it running to see whats the problem you are talking
about Maxim.




Em dom, 5 de ago de 2018 15:42, Maxim <notifications@github.com> escreveu:

**Comment by maxim-zhao** [comment]
OK, well I've done work on PAR before on SMS. Most emulators use a 1.0 ratio, but the TV signal has a pixel aspect ratio of 1.141 (NTSC) and 1.352 (PAL). Which are we targeting? Consider that the in-game art is clearly not scaled in the same way.

The screen is 256x240 internally but only 248x192 is displayed. Your emulator may be giving you some of the borders on screenshots.

I think it's better to keep the 1.0 ratio the game was made for, even if it's wrong. Nearly every SMS game is wrong in the same way.

**Comment by AlWesker** [comment]
I just did this retooling.

![imagen](https://user-images.githubusercontent.com/41370804/43691410-5cda2c8e-991c-11e8-8d23-137cd85fbc5b.png)

And it seems to fit fine this way, so why not? Apart from maybe recentering the Pimple text better. Those circles from the SNES version were too big anyway.

Plus I also fixed a little shade of blue that Rash had on his body for some reason.

**Comment by AlWesker** [comment]
Actually what seems to be uncentered is not the Pimple text but the Pimple artwork itself. But it's that way on the original SMS version, I just followed the same pattern. I noticed you fixed that when introducing the new artworks.

I suppose the end result with the retooling would be something more like this.

![imagen](https://user-images.githubusercontent.com/41370804/43691616-4d14c432-991f-11e8-9b8a-f65504279650.png)

**Comment by PyronsLair** [comment]
Maxim every game on SMS library will scale for 4:3 aspect ratio, as the
console as made and desinged for, wise pixel artists do the art thinking on
it, so like in the snes version they draw the art squeezed to look right on
TV, if they draw it perfect in that resolution the game gonna look worng on
tv like every bad games around there.

you only have the opition to play the game 1:1 resolution on emulators, if
you want see how it really looks adjust it to strech the image to 4:3
aspect window.

So for my is yes, is what we are looking for because real players or sms
lovers plays it on real hardware. Emulators players can adjust it easily
with one option.. real playres cant do that on real hardware so its not
fair do it..

SMS, NES, SNES,PC-engine dosent run games in hi res mode like mega drive so
we must care about it.



2018-08-05 21:02 GMT-03:00 Albert Wesker <notifications@github.com>:

**Comment by AlWesker** [comment]
I did another retooling as I found some inconsistencies within the circles.

![imagen](https://user-images.githubusercontent.com/41370804/43715880-486c8c22-9982-11e8-9f99-84e5cecbbd64.png)

It's difficult to make both match perfectly each other unless you redo them from scratch, but I see them fine this way overall.

**Comment by maxim-zhao** [comment]
SMS resolution is 256x192 (normally), which is nominally 4:3. However, on a PAL TV screen the rendered area is closer to 16:9. Games almost always do not compensate for this, either in the artwork or game engine. Emulators generally don't emulate this squashing - Kega is a notable exception.

It might be nice to offer artwork variants for all three pixel aspect ratio options, but I'd personally prefer to target only 1:1 for now, because I disagree that "real players or sms lovers plays it on real hardware". I will stick with this latest version for now, even if the characters are a bit stretched - because it actually looks OK, compared to their "normal" squashed look...

**Comment by AlWesker** [comment]
Wait. Use this instead.

![imagen](https://user-images.githubusercontent.com/41370804/43724298-e17cdd74-9999-11e8-8e90-d4931970af81.png)

I managed to make both circles look quite the same and with less rough edges. There are some very minmal pixel differences between both (made to suit the artworks a little better within) but it's hardly appreciable unless you look very close to them.

I don't think I'm able to make them look much better than that, plus they are quite aligned. The art doesn't actually give me the impression of being stretched and looks OK to me.

**Comment by AlWesker** [comment]
Wait. Please use this instead.

![imagen](https://user-images.githubusercontent.com/41370804/43724298-e17cdd74-9999-11e8-8e90-d4931970af81.png)

I managed to make both circles look quite the same and with less rough edges. There are some very minmal pixel differences between both (made to suit the artworks a little better within) but it's hardly appreciable unless you look very close to them.

I don't think I'm able to make them look much better than that without redoing the circles from scratch. Plus they actually look quite aligned now.

**Comment by PyronsLair** [comment]
Looks fine, so everything gonna be fixed in 256x192 right ?


2018-08-06 12:01 GMT-03:00 Albert Wesker <notifications@github.com>:

**Comment by PyronsLair** [comment]
So i redid the art using the sms resolution that Maxim have informed
I redid the circles and i put the players names bellow
the names font i take from battletoads arcade game
something maybe is not 100% aligned.. because i did just looking
i dont have good tools here.. but wesker can fix it for me.

take a look

https://i.imgur.com/wWUtqYy.png

2018-08-06 14:27 GMT-03:00 Gabriel Pyron <gabpyron@gmail.com>:

**Comment by AlWesker** [comment]
Hey, it's not a bad idea to use that fancy looking font from Battletoads Arcade. It gives points for series consistency for sure. 

Your circles look good enough to me. They are mirror matches of each other (something I couldn't achieve with mines, though mines are smaller and artworks don't fit so well inside them) with less rough edges and are perfectly aligned each other, so don't worry. No need to fix anything.

I don't know if the size of those circles is going to be a problem or not since those are still a little big. What do you think @maxim-zhao?

**Comment by AlWesker** [comment]
I just attempted do a selection screen mockup using those circles/artworks with the fancy fonts but it seems it's still too big. Take a look.

![imagen](https://user-images.githubusercontent.com/41370804/43735712-9e7b068c-99bb-11e8-95eb-bf47d18439a8.png)

Assuming we have a limit of space to use due to the fact that the selection texts are difficult to move and the omission of one of the two "2 Player" modes realocating the enemy fire function to the options is out of the question now, I suppose those circles still have to be a tad smaller. More like mines, maybe a little bigger than them but not too much either.

**Comment by AlWesker** [comment]
I just attempted do a selection screen mockup using those circles/artworks with the fancy fonts but it seems it's still too big. Take a look.

![imagen](https://user-images.githubusercontent.com/41370804/43735712-9e7b068c-99bb-11e8-95eb-bf47d18439a8.png)

Assuming we have a limit of screen space to use due to the fact that the selection texts are difficult to move and the omission of one of the two "2 Player" modes realocating the enemy fire function to the options is out of the question now, I suppose those circles still have to be a tad smaller. More like mines, maybe a little bigger than them but not too much either.

**Comment by PyronsLair** [comment]
OK tomorrow I do a new try..  But maybe they become oval.  Try put the
fonts on top instead maybe works

Em seg, 6 de ago de 2018 16:01, Albert Wesker <notifications@github.com>
escreveu:

**Comment by AlWesker** [comment]
Putting them on top doesn't solve the problem too much. It's like going back to the original problem in which there's not too much margin space between the elements.

![imagen](https://user-images.githubusercontent.com/41370804/43738411-d2c7b1d4-99c4-11e8-8495-a41e182cb490.png)

There's a possible alternative I thought of, and that's inserting the texts a little within the upper side of the circles. It looks remarkably good that way and leaves enough margin space in both sides.

![imagen](https://user-images.githubusercontent.com/41370804/43738480-167550d0-99c5-11e8-96cd-fa3dbe776369.png)

Again, these are just mockups of how they may considering only the screen space available. Maxim is the one who has to tell which would be the best approach considering the technical standpoint.

**Comment by PyronsLair** [comment]
I do something like the second screen,  looks cooler and better than a
floating text.  Tiles count is fine,  my first try we have a lot of free
space to use

Em seg, 6 de ago de 2018 17:09, Albert Wesker <notifications@github.com>
escreveu:

**Comment by maxim-zhao** [comment]
I redrew the circles a little and made this:
![image](https://user-images.githubusercontent.com/7792986/43808324-6d552d28-9aa4-11e8-858c-a22652cef987.png)
I think it's OK for now.
