### ISSUE TITLE
In-game score and lives digits

### ISSUE THREAD

**Issue by AlWesker** [maxim-zhao/battlemaniacs-restoration#23]
These are still using the old font. Shall we use the SNES font to replace them?

**Comment by maxim-zhao** [comment]
I think they're a different font. Should be easy to replace though.

**Comment by AlWesker** [comment]
This seems to be the score and live digits font of the SNES version.

![imagen](https://user-images.githubusercontent.com/41370804/43995201-30c1f9d2-9daa-11e8-92e3-7e3564d2c3d8.png)

The smaller ones are for the score and the bigger ones are for the lives, because the SNES version actually makes that difference. 

![imagen](https://user-images.githubusercontent.com/41370804/43995231-baaa9b7c-9daa-11e8-85f3-175bc7cb02d6.png)

The Master System version doesn't, and I suppose it's too much work to readapt that so I suppose we are fine with the smaller ones for both score and lives. 

But shall we use that specific score font or we'd rather use the other font of the intermissions? Something tells me it will be more convenient to use the intermission font, because that score font from the SNES seems to use kind of colored shade and maybe that won't look good on the Master System.

**Comment by maxim-zhao** [comment]
`So here's the SMS font, using pink for transparency here:
![image](https://user-images.githubusercontent.com/7792986/44007588-5bbeebf4-9e90-11e8-85df-421900aaa8da.png)
The game uses tiles for the top of the screen during horizontally-scrolling stages, but switches to using sprites during vertical scrolling (due to technical limitations), which requires it to do a nasty alternating effect (only one toad's data at once) and causes terrible flicker much of the time. It uses the sprite palette at all times.

The SNES numbers use shades of blue, but we don't have them available. Here it is with the closest match:
![image](https://user-images.githubusercontent.com/7792986/44007793-8f37665c-9e93-11e8-9720-2260b724d184.png)

And with greys:
![image](https://user-images.githubusercontent.com/7792986/44007801-97d4ac98-9e93-11e8-9506-7c762327a8d2.png)

In-game:
![image](https://user-images.githubusercontent.com/7792986/44007822-c74caf84-9e93-11e8-87ad-a1a4e38378bc.png)

![image](https://user-images.githubusercontent.com/7792986/44007833-d998077e-9e93-11e8-928f-693b670335be.png)

I think the blue is easier to read.

**Comment by AlWesker** [comment]
Yeah, not only the blue is easier to read but it's also closer to the SNES version, so good choice.

**Comment by AlWesker** [comment]
Not only the blue is easier to read but it's also closer to the SNES version, so good choice.

**Comment by PyronsLair** [comment]
Score points must use character pallete to save colors no?

Em dom, 12 de ago de 2018 21:53, Albert Wesker <notifications@github.com>
escreveu:

**Comment by maxim-zhao** [comment]
Correct.
