### ISSUE TITLE
Ending script

### ISSUE THREAD

**Issue by maxim-zhao** [maxim-zhao/battlemaniacs-restoration#3]
Should be a matter of repurposing the intro engine, but I didn't disassemble to find its location yet.

**Comment by AlWesker** [comment]
I noticed you inserted the text of the bad ending on the ROM, even though that part of the text will probably go unused. Are you planning to do something that could make the ending fork into either the good ending or the bad ending of the SNES version (the SNES version does that with a little gameplay section in which you have to destroy the Silas Volkmire's ship, this is of course totally missing on the Master System version), or are you just going to set a fixed ending leading always to the good ending?

**Comment by maxim-zhao** [comment]
I didn't know what caused it to have the bad ending. I guess we could tie it to something else - maybe you get the good ending if you don't use any continues, for example.

**Comment by AlWesker** [comment]
The SNES version has a little gameplay section at the ending in which you have to fire the Silas Volkmire ship. You have to hit it three times, you are on a timer and the chrosshair moves and you have to press it at the right time. If you fail, the ship escapes and you have the bad ending. If you win, you destroy it and you have the good ending.

Take a look: https://www.youtube.com/watch?v=Gx9QZ-VeF0U

I take it this is hard to implement as it would require a sprite engine instead of the static screens we are doing. So that's why I suggested to just use the good ending instead, as there isn't much of a difference between one ending or the other. 

The idea of not using continues to trigger the good ending is not bad, but if we do something like that I'd rather prefer to link the endings to the difficulty selections as that's something many games did back in the day. I suggest the easy difficulty having no ending at all (so the game would end after the last intermission scene as it's right now), normal difficulty leading to the bad ending and hard difficulty leading to the good ending. The hard difficulty has no continues at all so it would be similar to what you said. This would also try to compensate the overall lack of challenge that the Master System version has in comparison to the ultra hard SNES version.

**Comment by maxim-zhao** [comment]
I think porting the ending is achievable but we should probably not expect it for now, I want to finish this project sooner rather than later :)

**Comment by AlWesker** [comment]
The original ending with the gameplay mechanic? Yeah, maybe for a future update. Same for other more complex aspects. But from now on, if you agree with the endings being tied to the difficulty selections, we can put them as separate sequences that way. I think it's a good approach.

**Comment by maxim-zhao** [comment]
I'm going to close this one as the ending is done, albeit only in the "good" form.

**Comment by AlWesker** [comment]
Cool! With this, one of the major flaws of the Master System version has been restored.

Everything's ok outside of still using placeholder images, but I wonder if it would be possible to place all the "And so, the sinister Silas Volkmire was blablabla" text with a starfield background. After all, the SNES version uses the starfield background for that section of the ending.

What should we do with the bad ending? We leave it unused? We add them according to the difficulty levels like I suggested (Easy: no ending, Normal: bad ending, Hard: good ending)? Or we wait to have the original gameplay mechanic from the SNES version hopefully implemented some day?

And I have to admit I wasn't expecting those "Special Thanks" lines of the credits. It's a good touch. I suppose that's an homage to the SNES intro which does some credits, even though in that case they credit the bad guys too. Should we include them or we leave them with the good guys only?

**Comment by maxim-zhao** [comment]
I was just channeling some of the endings you'd see on games in those days, although I guess it's a more Japanese style. I'm not overly bothered too keep it or change it, to be honest.

**Comment by AlWesker** [comment]
Actually, the ports that were done of the home version Battletoads games for the Game Boy also did the same, putting the ending text in a black background even though the original ones for home consoles (NES or Mega Drive usually) were placed in a starfield. But since the Battletoads series seems to have a common starfield theme among all the installments, I have a feeling the changes in the Game Boy conversions were done to fit the screen and color limitations of the portable console rather than an artistic decision. Compare:

NES Battletoads

https://www.youtube.com/watch?v=afzhivak9AQ

Game Boy Battletoads (this version is named Battletoads in Ragnarok's World)

https://www.youtube.com/watch?v=fmhg0x40a8s

NES Battletoads Double Dragon

https://www.youtube.com/watch?v=K1ZM0twwpM8

Mega Drive Battletoads Double Dragon

https://www.youtube.com/watch?v=-6H5DksIXeA

Game Boy Battletoads Double Dragon

https://www.youtube.com/watch?v=8OxdYw6smkk

And of course, there's the original SNES ending of Battletoads in Battlemaniacs with the starfield.

https://www.youtube.com/watch?v=gDC78GTwVLA

So I suppose either of the two ways would be fine but the starfield background would fit better not only with the SNES version of Battletoads in Battlemaniacs but also with the rest of home consoles installments of the series. I'm only worried by the fact that it may difficult reading the text, but if it's not the case, then go ahead.

**Comment by maxim-zhao** [comment]
Let's make a v2 issue for the credits.
