### ISSUE TITLE
Glitches in SFX

### ISSUE THREAD

**Issue by maxim-zhao** [maxim-zhao/battlemaniacs-restoration#4]
> By the way, I just did some test on the console and the implementation of sound effects seems to be complete but there are some weird sounds getting in the middle of the sound output. I'll try to explain/detail. 
> 
> Generally, when you perform an attack (either on ground or on air), a dinging sound gets on the middle. It's especially noticeable with attacks on ground but the attacks on air are faulty too. Sometimes, at very rare occassions, the punching sound comes right but normally the dinging goes along. And other weird noises are also noticeable when hitting enemies. 
> 
> In certain levels, like the Turbo Tunnel when you die or the snake levels when a snake go into a hole, there's also weird sounds being played. The snake sound is like some sort of bumping sound and it's very noticeable. 
> 
> Other than that, the sound implementation seems to be fine until I notice something else in a second playthrough.

**Comment by AlWesker** [comment]
I have done a comparative video between the original version with the Restoration hack in which you can notice the sound effect oddities described in that message. 

At first I was only going to compare non-music versions of both, but then I noticed that if you turn off the music in the Restoration hack, the sound effects actually come fine. Or almost fine, since sometimes they have some imperfection. So the problem comes when there's music, and the result of combination between both. 

There's four sound effects which are the most affected by either a "dinging" sound or some kind of high pitched explosion. The video shows four possible situations of these sound effects, first with the original version without music, then with the Restoration hack without music and then with the Restoration hack with music  (the different font can also be a help to distinguish them). Then I also play all the sounds in the sound test between original version with music and Restoration hack with music, since I wasn't able to find the value to disable the music of the title screen.

https://mega.nz/#!al5wDACR!toS5XXLkBB2AVkCe-tamG3N7EP1ALiol-Phngxcjll0

**Comment by PyronsLair** [comment]
Nice,  when I come in home I will test it.  Have some patience in the
others screens because they are much more complex, but is looking good.  I
think that you gonna like it,  but I will need your help

Em qua, 10 de out de 2018 14:22, Albert Wesker <notifications@github.com>
escreveu:

**Comment by AlWesker** [comment]
Hey @PyronsLair. I suppose you were going to put that message somewhere else because it's not related to this issue, but good to know. 👍

**Comment by PyronsLair** [comment]
yes, worng psot sorry

Em qua, 10 de out de 2018 às 14:36, Albert Wesker <notifications@github.com>
escreveu:

**Comment by maxim-zhao** [comment]
The SFX glitches are due to bugs in the VGM files. Several of them use noise in "tone controlled" mode, but do not silence the tone channel when doing that. I guess they need to be re-ripped.

**Comment by AlWesker** [comment]
Oh dear, that sounds bad, no pun intended.

Is this a problem only happening with the five original music tracks by Matt Furniss, or it's also happening with the four new ones that @MotavianRaider did? I guess we shouldn't worry by the T. Bird music by @sanchez-david since that one is never going to be used in any level/gameplay section anyway.

**Comment by maxim-zhao** [comment]
It's just the SFX. I used some tools to automatically rip them but those tools didn't correctly initialise things.

**Comment by AlWesker** [comment]
Oh, right. Can you take care of that or do I have to look for a solution?
