### ISSUE TITLE
Title screen modifications

### ISSUE THREAD

**Issue by maxim-zhao** [maxim-zhao/battlemaniacs-restoration#6]
We want to amend the title screen a little to label it as "Restoration Edition".

**Comment by AlWesker** [comment]
Do you like "Restoration Edition" more than "Restoration Project" for the title screen?

**Comment by maxim-zhao** [comment]
I would just go with "Battletoads Restoration".

**Comment by AlWesker** [comment]
You mean the Battlemaniacs logo and a "Restoration" line of text below?

**Comment by maxim-zhao** [comment]
Yes - I'm working on the title screen now so I can try a few things out soon.

**Comment by AlWesker** [comment]
If you are with that, I suppose you noticed already the problem with the revamped Battlemaniacs logo that come from the SNES. It surpasses tiles and Pyron is not able to downsample it.

I actually have an idea but I don't know if it will be feasible due to the tile count. Now the intended pre-title and title screen sequences are these according to the script.

Scene 4:

PRESENTS

ZITZ, RASH & PIMPLE

AS THE

BATTLETOADS

IN



Scene 5:

BATTLEMANIACS™ (logo)

RESTORATION PROJECT



PRESS START



LICENSED BY

SEGA ENTERPPRISES, LTD.

--------------------

It can be either RESTORATION PROJECT or RESTORATION if you prefer that. But I'm thinking in maybe another option even that will probably be even harder to squeeze on the Master System.


Scene 4:

PRESENTS

ZITZ, RASH & PIMPLE

IN



Scene 5:

BATTLETOADS IN BATTLEMANIACS™ (logo)

RESTORATION PROJECT



PRESS START



LICENSED BY

SEGA ENTERPPRISES, LTD.

---------------------------------------------------------

Scene 4 would be as it's now, simply fixing the PRESENT (because it's supposed to be Virgin Interactive Entertainment PRESENTS, therefore it's singular) and ZITS (ZITZ) typos, whereas in Scene 5 the Battlemaniacs logo would be replaced by the more complete BATTLETOADS IN BATTLEMANIACS logo from the boxart restoring the full title of the game.

Granted, if resampling the BATTLEMANIACS logo from the SNES title screen to fit the tile count is already going to be difficult, then I guess getting the BATTLETOADS IN BATTLEMANIACS logo from the boxart 
![imagen](https://user-images.githubusercontent.com/41370804/43672403-69b3fc66-97ad-11e8-98d5-e0c3fe2a917b.png) and adapt it to the game graphics/tile count may be even more harder. But I can tell Pyron and see if he's willing to try. 

What do you think about it?

**Comment by maxim-zhao** [comment]
Take a look at the most recent version - I have rearranged things and now we can have 370 tiles per screen, so the SNES logo fits easily. In addition, I have produced an entirely bitmapped title screen using proportional width fonts which allows us to fit text in more comfortably. What do you think?

I think my version is a proof of concept - a real artist can do a much better job. It's also worth considering if we should remake the preceding screens in the same way - all the text could fit in a single screen. Static starfields are an option too. It's (ab)using our copious free space, we are spending a few KB for every such screen.

**Comment by AlWesker** [comment]
Great job!

If the preceding screens are going to use a nicer font like the one the title screen has, then yeah, maybe it's worth a try. And maybe they would fit better with the starfield. I'll be uploading the starfield screen for you to try. By the way, how much free space is this taking? Do you fear it's going to end soon taking in mind that we still add to add the ending artworks and replace some of the artworks like the Rash and Pimple ones? I wouldn't like this hack to go beyond the 512 kb target, that would be too much to handle for Master System cartridge size and would difficult cartmodding the game.

I have to admit that I'm inclined to use the fuller Battletoads in Battlemaniacs logo from the SNES boxart rather than the simpler Battlemaniacs logo from the SNES title screen, but maybe that would a a monstrousity of tiles (Pyron is currently looking into that) and I would also like an opinion regarding it. What do you think it would be best, have the SNES Battlemaniacs title screen logo like it's now or going even further with the full Battletoads in Battlemaniacs logo from the SNES boxart? I like the latter much more as it gives the full title of the game in a much more visual way than it is now. Plus, the screen with "Presents Zitz, Rash & Pimple as the Battletoads in" could go back to "Presents Zits, Rash & Pimple in". But maybe we would be further detracting the idea of replicating the SNES assets doing that because after all, the SNES title screen doesn't use that boxart logo in the title screen.

There's a couple of side effects (or bugs if you prefer) that have been generated in the last version:

The title screen lost the music when you boot. But actually, if the game goes to the title screen coming from the Game Over screen, since the Game Over screen triggers the title screen, there's a effect produced which I like. Before, the original game had a trigger on the Battlemaniacs logo screen that would reset the title screen music, so if you loop the game into copyright screens, title screen, intro and so on, you would always have the title screen being interrupted and restart again when the Battlemaniacs logo appear. But now, given that this trigger is not in place, you can have the title screen music playing without interruption during the copyright screens, title screen and intro, but only if you come from a Game Over screen as that makes the title screen play which is currently disabled at boot. I don't know if I explained that well. You can appreciate better what I say if you start the game, force Game Over and see how the copyright screen, title screen and intro behave with the title screen music now in that case.

Also, the Pimple and Rash artworks from the selection screen lost the "Pimple" and "Rash" names that were placed above them. It's true the SNES version didn't show their names there in the equivalent screen of that version, but I liked that little touch that was added there in the Master System version. Can you add those back?

**Comment by AlWesker** [comment]
On a second thought about the "the Pimple and Rash artworks from the selection screen lost the "Pimple" and "Rash" names that were placed above them", actually we can do something else. In Issue #10 you mentioned that adding a toad select screen to manually select the toads (so that Player 1 isn't always fixed to Pimple and Player 2 isn't always fixed to Rash). If that's going to be added, then we could leave the selection screen as it is right now, without the names of Pimple and Rash over their artworks (like they are on the SNES version) and when you enter the selection screen, the names would appear over their artworks to remark better the toad that you are going to choose. That would be a good option I think.

**Comment by maxim-zhao** [comment]
The names were removed by accident, they're back now. 

The space is not really an issue, we have used about 100KB of the extra 256KB so far.

The music trigger for the title screen should be easy to fix, but I need to understand the game over flow as it may have some impact.

We could relocate the "Battletoads in" to the top of the title screen, but again it is not faithful to the SNES version.

**Comment by AlWesker** [comment]
The game over screen on the Master System version triggers the title screen music and if you don't continue, then the copyright/title screen/intro screens continue from there. Originally, the copyright screens would keep the music of the game over screen uninterrupted as they don't really have a music value of their own (that's why they are silent when you boot the game and why they won't override the music that's coming from the Game Over screen), while the title screen would restart it as it has a music value for the title screen music.

But now that I think about it, you are probably going to insert the game over intermission scenes (the ones of the Dark Queen and T Bird talking in case you don't continue or you run out of continues, those are still unimplemented) after the game over screen so that is going to have to change. And the game over screen on the SNES version had a music which is the same of the intermissions (see it here: https://www.youtube.com/watch?v=SLZS3fUg06g). That music will probably be converted by S T A R when he has the time to it so this would have to be different.

I think the best option to mirror the SNES version is going to be having the intermissions and the game over screens playing the still unimplemented music (which still has to be composed, so until that they will have to be silent), and adding the title screen music value in the first copyright screen, not in the title screen as it's now. This would make the title screen music play at boot, though that's exactly what the SNES version does (see it here: https://www.youtube.com/watch?v=-bul0lZcPuY).

But I suppose that doing that would make the title screen music always reset at the first copyright screen, even if coming from the intro. That's actually what the SNES version does like you can see in the YouTube video. But in this case I would prefer that if you come from the intro, the title screen music wouldn't reset so it would keep playing uninterrupted if you leave the game in "demo mode" (that is, playing the copyright screens/title screen and intro on a permanent loop). Would this be possible?

**Comment by AlWesker** [comment]
About the "Battletoads in" in the title screen, yeah, that can be an option, but I'm going to see if it's possible for Pyron to convert the "Battletoads in Battlemaniacs" full logo of the boxart (ie, this 
![imagen](https://user-images.githubusercontent.com/41370804/43672408-8465d980-97ad-11e8-92d0-66152763f523.png) as it would be much better visually that way. If it's too much out of the scope tile wise even with the larger tile count that we now have, then we keep the current Battlemaniacs logo from the SNES title screen with a "Battletoads in" text over it like you said.

**Comment by maxim-zhao** [comment]
Finished, I think,
![image](https://user-images.githubusercontent.com/7792986/43808522-5f15d59a-9aa5-11e8-908b-a718559ffa23.png)
