### ISSUE TITLE
Pre-title modifications

### ISSUE THREAD

**Issue by maxim-zhao** [maxim-zhao/battlemaniacs-restoration#7]
* Correct Zits => Zitz
* Add "Battletoads In" before the title screen
* Anything else not matching the wanted script

Should we just reimplement it using the script engine?

**Comment by AlWesker** [comment]
"Should we just reimplement it using the script engine?"

What are the enhancements of doing it that way? Maybe it would allow to have a starry sky background like the SNES version does instead of a plain black one like the current SMS one?

**Comment by maxim-zhao** [comment]
The script engine in its current form is used for the intro, intermissions and game over screens; it allow syou to draw static pictures and text and insert delays. Special effects - picture animations and background effects - would be "extra".

To draw the (animated) starfield would be a bit tricky as the SMS doesn't have the hardware layers support the SNES has. We could fake it with sprites, similar to the Wonder Boy III ending sequence, but the starfield would have to lose some density ad it would require running a sprite engine during those sequences, which may be tricky to fit in with the game engine. Alternatively we could throw a starfield picture up and draw text over the top... but we'd still have cuts to black.

**Comment by AlWesker** [comment]
So the Game Over screens are going to be modified too. That's great. I wonder if it's just to add the missing Game Over intermission-like scenes with the Dark Queen and T Bird or can the Game Over screen itself be modified. It's because the Master System Game Over screen reuses the title screen artwork for both Pimple and Rash while the SNES Game Over screen had its own artwork. Take a look at the difference.

SNES 

![imagen](https://user-images.githubusercontent.com/41370804/43672419-b6d774b4-97ad-11e8-9501-0e93583cfa8b.png)

Master System

![imagen](https://user-images.githubusercontent.com/41370804/43672420-bfb8f3aa-97ad-11e8-94c8-5e84498f20f8.png)

Regarding the starfield, the sprite engine maybe sounds a little too complicated to attempt. Maybe we can do a test with the starfield picture and drawing text and see if it fits good that way. I'll upload a converted starfield to use as test.

**Comment by maxim-zhao** [comment]
I did end up reimplementing it using the same engine, it's almost identical except I didn't make it possible to have unskippable screens yet :) and I can't delay more than 256 frames, whereas the original makes you stare at each screen of text for 6 seconds... I'm inclined not to bother with those aspects though.

**Comment by maxim-zhao** [comment]
By the game over screen I meant the pre continue screen... But I will get to the game over screen.
